package com.victxl.curso.services.exceptions;

public class ResourceNotFoundException extends RuntimeException {

    public ResourceNotFoundException(Object id) {
        super("Recurso n√£o encontrado: Id = " + id);
    }

}
